---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: grower-ui
    app.kubernetes.io/instance: grower-ui
  name: grower-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grower-ui
      app.kubernetes.io/instance: grower-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grower-ui
        app.kubernetes.io/instance: grower-ui
    spec:
      containers:
      - image: vi7al/iot-env:0.9.2
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: grower-ui
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
      # nodeSelector:
      #   kubernetes.io/os: linux
      nodeName: fuel.home
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: grower-ui
    app.kubernetes.io/name: grower-ui
  name: grower-ui
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: grower-ui
    app.kubernetes.io/name: grower-ui
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: grower-ui
    app.kubernetes.io/name: grower-ui
  name: grower-ui
  namespace: default
spec:
  rules:
  - host: grower-ui.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grower-ui
            port:
              number: 80
