{
 "title": "Prod Grower",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Air temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "htu2xd_temp_celsius{job=\"arduino-grower\"}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "htu2xd_humidity_percent{job=\"arduino-grower\"}"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Environment data",
   "type": "graph",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "htu2xd_temp_celsius{job=\"arduino-grower\"}",
     "legendFormat": "temperature"
    },
    {
     "expr": "htu2xd_humidity_percent{job=\"arduino-grower\"}",
     "legendFormat": "humidity"
    }
   ]
  },
  {
   "title": "Temperature read errorrate",
   "type": "timeseries",
   "description": "Temperature read errors per minute",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "err/min" } },
   "targets": [
    {
     "expr": "irate(htu2xd_temp_read_errors_total{job=\"arduino-grower\"}[5m])*60"
    }
   ]
  },
  {
   "title": "Humidity read errorrate",
   "type": "timeseries",
   "description": "Humidity read errors per minute",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "err/min" } },
   "targets": [
    {
     "expr": "irate(htu2xd_humidity_read_errors_total{job=\"arduino-grower\"}[5m])*60"
    }
   ]
  }
 ]
}